world:
  name: islands
  island-height: 100
  island-distance: 250
  island-size: 100

creation:
  max-concurrent: 3
  threads: 3

schematics:
  default: classic
  list:
    classic:
      display-name: "&aClassic"
      file: classic.schem
      home-offset:
        x: 0.5
        y: 5.0
        z: 0.5
    desert:
      display-name: "&eDesert"
      file: desert.schem
      home-offset:
        x: 0.5
        y: 5.0
        z: 0.5

storage:
  type: sqlite
  mysql:
    host: localhost
    port: 3306
    database: skyblock
    username: root
    password: ""
    ssl: false
